services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: roadmap_ai_v2
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

  roadmap-ai:
    build: .
    container_name: roadmap-ai
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ROADMAP_AI_JWT_KEY=${ROADMAP_AI_JWT_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always

volumes:
  mysql_data:
